spring:
  application:
    name: user-service

  cloud:
    compatibility-verifier:
      enabled: false
    config:
      enabled: false
    kafka:
      bootstrap-servers: localhost:9092

server:
  port: 8088

eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka
