version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  discovery-server:
    image: muratbek2255muratkanov/discovery-server.jar
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: muratbek2255muratkanov/api-gateway.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    depends_on:
      - discovery-server

  authentication-postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - authentication-service/.env
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always

  chat-postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - chat-service/.env
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always

  course-postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - course-service/.env
    ports:
      - "5432:5432"
    command: -p 5432
    restart: always

  exam-postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - exam-service/.env
    ports:
      - "5433:5433"
    command: -p 5433
    restart: always

  library-postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - library-service/.env
    ports:
      - "5434:5434"
    command: -p 5434
    restart: always

  payment-postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - payment-service/.env
    ports:
      - "5434:5434"
    command: -p 5434
    restart: always

  user-postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - user-service/.env
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always

  authentication-service:
    image: muratbek2255muratkanov/app.jar
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - SPRING_DATASOURCE_URL=jdbc:postgresql://authentication-postgres:5431/new_project_db
    depends_on:
        - authentication-postgres
        - discovery-server
        - api-gateway

  chat-service:
    image: muratbek2255muratkanov/chat.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://chat-postgres:5431/new_project_db
    depends_on:
      - chat-postgres
      - discovery-server
      - api-gateway

  consumer-service:
    image: muratbek2255muratkanov/consumer.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - broker
      - zookeeper

  course-service:
    image: muratbek2255muratkanov/course.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://course-postgres:5431/course_db
    depends_on:
      - course-postgres
      - discovery-server
      - api-gateway

  exam-service:
    image: muratbek2255muratkanov/exam.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://exam-postgres:5431/exam_db
    depends_on:
      - exam-postgres
      - discovery-server
      - api-gateway

  library-service:
    image: muratbek2255muratkanov/library.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-postgres:5431/book_library
    depends_on:
      - library-postgres
      - discovery-server
      - api-gateway

  payment-service:
    image: muratbek2255muratkanov/payment.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-postgres:5431/book_library
    depends_on:
      - payment-postgres
      - discovery-server
      - api-gateway
      - zookeeper
      - broker

  user-service:
    image: muratbek2255muratkanov/user.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgres:5431/new_project_db
    depends_on:
      - user-postgres
      - discovery-server
      - api-gateway

volumes:
  postgres_data:

networks:
  my-network: