spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/your_database
    driver-class-name: org.postgresql.Driver
    username: your_username
    password: your_password

  cloud:
    compatibility-verifier:
      enabled: false
    config:
      enabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084


eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka
