server:
  port: 8888
  servlet:
    context-path: /config

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761

spring:
  application:
    name: config-service
